services:
  mysql:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: OFS_DB
      MYSQL_ROOT_PASSWORD: RootPassword123!
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"  # Maps host port 3307 to container port 3306
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server","--appendonly","yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: .env.server
    ports:
      - "4000:4000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL","curl -f http://localhost:4000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
    restart: unless-stopped
volumes:
  db_data:
  redis_data:
